tap "derailed/k9s", trusted: true
tap "minio/stable", trusted: true
tap "supabase/tap", trusted: true
brew "bat"
brew "ripgrep"
brew "cloudflared"
brew "codex"
brew "eza"
brew "fd"
brew "fzf"
brew "node"
brew "git"
brew "go"
brew "herdr"
brew "kind"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "libavif"
brew "libmagic"
brew "minikube"
brew "minio"
brew "neovim"
brew "pnpm"
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "tmux"
brew "mole"
brew "yarn"
brew "redis"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "derailed/k9s/k9s"
brew "minio/stable/mc"
brew "supabase/tap/supabase"
cask "codex"
cask "ghostty"
cask "ngrok"
cask "vlc"

