set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"
set -gq allow-passthrough on

set -g base-index 1
set -g pane-base-index 1

set-option -g prefix C-a
set-option -g prefix2 none

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind %
bind = split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind v
bind v copy-mode

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

bind s choose-session

set -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key n command-prompt "new-session -s '%%'"

unbind -T copy-mode-vi MouseDragEnd1Pane

set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/.tmux/plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "christoomey/vim-tmux-navigator"

# Theme: catppuccin mocha
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_number "#[bold]#{?#{!=:#{window_name},},#I. #W,Tab ###I} "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_current_number "#[bold]#{?#{!=:#{window_name},},#I. #W,Tab ###I} "
set -wg automatic-rename on
set -g automatic-rename-format ''
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

set -g window-status-separator ""
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold]TMUX (#S) "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""

# bootstrap tpm
if "test ! -d ~/.config/tmux/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/.tmux/plugins/tpm && ~/.config/tmux/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/.tmux/plugins/tpm/tpm'