# source "$HOME/.config/zsh/.zshrc"
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
plugins=(git)

source $ZSH/oh-my-zsh.sh

export TMUX_CONF=~/.config/tmux/tmux.conf
alias ragworks='cd ~/Ragworks/ && ./ragworks_tmux.sh'
alias ls='eza --no-filesize --long --color=always --icons=always --no-user' #List  directory
alias lh='eza -dl .* --group-directories-first --icons' #List hidden directory
alias ll='eza -al --group-directories-first --icons' #List long directory with directory first
alias lt='eza -al --sort=modified --icons' #List long directory sorted by modified time
alias c='clear'
alias e='exit'
alias gcl="git clone"
alias ga="git add"
alias gaa="git add ."
alias gaaa="git add --all"
alias gau="git add --update"
alias gb="git branch"
alias gbd="git branch --delete "
alias gcm="git commit --message"
alias gcf="git commit --fixup"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gi="git init"
alias gm="git merge --no-ff"
alias gma="git merge --abort"
alias gmc="git merge --continue"
alias gp="git pull"
alias gpo="git pull origin"
alias gpuo="git push origin"
alias gpr="git pull --rebase"
alias gr="git rebase"
alias gss="git status --short"
alias gst="git stash"
alias gsta="git stash apply"
alias gstd="git stash drop"
alias gstl="git stash list"
alias gstp="git stash pop"
alias gsts="git stash save"
alias gs="git status"
alias pi="pnpm install"
alias ps="pnpm start"
alias prd="pnpm run dev"
alias pr="pnpm run"
alias px="pnpx"
alias bs="bun start"
alias ns="npm start"
alias nrd="npm run dev"
alias brd="bun run dev"
alias nr="npm run"
alias br="bun run"
alias nil="npm install --legacy-peer-deps"
alias dps="docker ps"
alias de="docker exec -it"
alias h='herdr'
alias hss='herdr server stop'
alias tmux="tmux -f $TMUX_CONF"
alias tns="tmux new -s"
alias td="tmux detach"
alias tls="tmux ls"
alias ta="tmux attach -t"
alias tka="tmux kill-server"
alias tks="tmux kill-session -t"
alias cat='bat'
alias sourcezsh='source ~/.zshrc'

eval "$(fzf --zsh)"
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git "
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"
export FZF_DEFAULT_OPTS="--height 50% --layout=default --border --color=hl:#2dd4bf"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always -n --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --icons=always --tree --color=always {} | head -200'"
export FZF_TMUX_OPTS=" -p90%,70% "  

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

eval "$(zoxide init zsh)"

export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

export PATH="$PATH:$HOME/.local/bin"
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=($HOME/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"

# kilo
export PATH=$HOME/.kilo/bin:$PATH
